### ISSUE TITLE
Usable without Redis?

### ISSUE THREAD

**Issue by adaszko** [scr34m/proof#1]
Hi 👋 

Let me start by saying this is a great idea for a project!  I'm trying to deploy it to a small ARM64 SBC to monitor my projects and can't get it to show any exceptions.  I've configured `proof.toml`, initialized the SQLite database schema by hand, initialized Sentry SDK in my Python project and I don't see `POST` requests with exceptions arriving at Proof's end (based on its logs).  I haven't deployed/configured Redis for it, thus my question: is the project usable without Redis?  Putting everything in SQLite would be more than enough for my needs.

As an aside, I'm also getting a panic when I try to `/login` via web browser:
```
[POST] "/login" 637.583µs
panic: runtime error: invalid memory address or nil pointer dereference
```

Thank you!

**Comment by scr34m** [comment]
Yes redis is not mandatory, i'm running this on local dev machine like this: `./proof -listen=:2017 -database=proof -database-type=mysql -database-user=root`

**Comment by adaszko** [comment]
> Yes redis is not mandatory, i'm running this on local dev machine like this: `./proof -listen=:2017 -database=proof -database-type=mysql -database-user=root`

Thanks! Would you mind sharing how you roughly configure the sentry sdk?

**Comment by scr34m** [comment]
Just setting the URL like this: http://a4f7646fd83544dd9499c18561338d56:62b2a152380044f28753c26a83cf2ee3@127.0.0.1:2017/2

**Comment by adaszko** [comment]
Thank you!
